Reinforce:
    #等级设置
    Level:
        #+1时的情况
        #比前一级提升的数量
        #10%写为0.1
        '1': 
            #比前一级提升的数量
            Power: 0.1
            #基础概率
            Probability: 0.5
        '2': 
            #比前一级提升的数量
            Power: 0.1
            #基础概率
            Probability: 0.4
        '3': 
            #比前一级提升的数量
            Power: 0.1
            #基础概率
            Probability: 0.3
        '4': 
            #比前一级提升的数量
            Power: 0.1
            #基础概率
            Probability: 0.2
        '5': 
            #比前一级提升的数量
            Power: 0.1
            #基础概率
            Probability: 0.1
        '6': 
            #比前一级提升的数量
            Power: 0.1
            #基础概率
            Probability: 0
        '7': 
            #比前一级提升的数量
            Power: 0.1
            #基础概率
            Probability: -0.1
Scroll:
    #卷轴的键值 需要独一无二 命令获取物品用的东西
    putong:
        #物品的样式
        Item: '339 1 0 Name:&6普通强化卷轴 Lore:&a直接强化至+5|&c强化成功概率:_50%'
        #强化到的级别
        To: 5
        #强化成功几率  1为100%
        Success: 0.5
Gem:
    #宝石的键值 需要独一无二 命令获取物品用的东西
    baoshi:
        #物品样式
        Item: '388 1 0 Name:&6普通强化宝石 Lore:&a强化等级_+1|&b最大强化等级:_3|&c强化成功概率_10%'
        #最大强化到的等级
        Max: 3
        #强化成功几率
        Success: 0.1
Protect:
    #保护卷轴的键值
    baohu:
        #物品样式
        Item: '339 1 0 Name:&6普通保护卷轴 Lore:&a最大保护等级:_3|&b能保证强化失败后武器不损毁'
        Max: 3