# 购买者条约:
# 作者: Brayn_lzh
# QQ: 390807154
# 保修规则:
#   插件永久修复错误(在合理程度内 非买方误操作 非服务端本身问题)
#   包1年内MC版本更替修复
#   对修改过代码的不保修
#   需要保修时请说明问题 务必附上报错内容
#   若需要添加新功能将进行最低量的收费
# 你可以:
#   1.声明这个插件是私用的
#   2.利用本插件向玩家盈利
#   3.修改本插件代码
# 你不可以:
#   1.声明这个插件是你写的
#   2.不能通过卖本插件盈利
# 有可能在不通知您的情况下对本插件进行修改后卖给他人(一般都会通知 并且将返回部分钱)
# 对应不在本条约里的事项请向我联系
name: Reinforce
author: Bryan_lzh
main: Br.Reinforce.Main
description: '开发者QQ:390807154'
depend: [BrAPI,SkillAPI]
version: 1.0

commands:
    Reinforce:
        aliases: [rein]
        description: 主命令
        usage: |
            §6/<command> >> 打开强化界面
            §6/<command> give [玩家] [s/g/p] [键值] (数量) >> 给予玩家一个物品 s代表卷轴g代表表示p代表保护卷轴